const SB_URL='https://yhvfguhgbxinphcvbjax.supabase.co';
const SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodmZndWhnYnhpbnBoY3ZiamF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODQyMTEsImV4cCI6MjA3NDY2MDIxMX0.CVZQMcMcyl4o5saYcOgFheIhTnAyerO3BR3sc';
const H={apikey:SB_KEY,Authorization:'Bearer '+SB_KEY,'Content-Type':'application/json'};
let apps=[],memos=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function login(e){e.preventDefault();const p=document.getElementById('adminPassword').value.trim();if(p==='farabi1@'||p==='1786'){sessionStorage.setItem('farabi_demo_admin','1');show()}else alert('ভুল পাসওয়ার্ড! সঠিক ডেমো পাসওয়ার্ড দিন।')}
function show(){loginGate.style.display='none';layout.style.display='flex';if(window.lucide)lucide.createIcons();loadApps();loadMemos();newMemoNo();previewMemo()}
function logout(){sessionStorage.removeItem('farabi_demo_admin');location.reload()}
function tab(id,btn){['apps','memo','info'].forEach(x=>document.getElementById(x).style.display=x===id?'block':'none');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(id==='memo')loadMemos()}
async function api(path,opt={}){const r=await fetch(SB_URL+'/rest/v1/'+path,{...opt,headers:{...H,...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
async function loadApps(){tbody.innerHTML='<tr><td colspan="8" class="empty">ডাটা লোড হচ্ছে...</td></tr>';try{apps=await api('applications?select=*&order=created_at.desc');db.textContent='ক্লাউড সক্রিয়';db.style.color='#16a34a';dbdesc.textContent='Supabase connected';renderApps(apps)}catch(e){db.textContent='ত্রুটি';db.style.color='#dc2626';dbdesc.textContent='Supabase connection failed';tbody.innerHTML='<tr><td colspan="8" class="empty">Supabase ডাটা লোড করা যায়নি।</td></tr>';console.error(e)}}
function renderApps(list){count.textContent='মোট রেকর্ড: '+list.length+' টি';total.textContent=apps.length;const d=new Date().toISOString().slice(0,10);today.textContent=apps.filter(a=>a.created_at?.slice(0,10)===d).length;office.textContent=apps.filter(a=>(a.course||'').includes('অফিস')).length;if(!list.length){tbody.innerHTML='<tr><td colspan="8" class="empty">কোনো আবেদন পাওয়া যায়নি।</td></tr>';return}tbody.innerHTML=list.map((a,i)=>{const ph=String(a.phone||'').replace(/\D/g,'');const st=a.status||'new';return `<tr><td>${i+1}</td><td><strong>${esc(a.id)}</strong></td><td><strong>${esc(a.full_name)}</strong></td><td><a href="tel:${ph}" style="color:var(--p);font-weight:700">${esc(a.phone)}</a></td><td>${esc(a.course)}</td><td>${a.created_at?new Date(a.created_at).toLocaleDateString('bn-BD'):'---'}</td><td><select class="status ${st}" onchange="setStatus('${a.id}',this.value)"><option value="new" ${st==='new'?'selected':''}>নতুন</option><option value="pending" ${st==='pending'?'selected':''}>অপেক্ষমাণ</option><option value="approved" ${st==='approved'?'selected':''}>গৃহীত</option><option value="rejected" ${st==='rejected'?'selected':''}>বাতিল</option></select></td><td><div class="row-actions"><a class="icon-btn wa" target="_blank" href="https://wa.me/88${ph}?text=${encodeURIComponent('হ্যালো '+(a.full_name||'')+', ফারাবী আইটি সেন্টার থেকে আপনার ভর্তি আবেদন সম্পর্কে যোগাযোগ করা হচ্ছে।')}">◉</a><a class="icon-btn call" href="tel:${ph}">☎</a><button class="icon-btn view" onclick="viewDetail('${a.id}')">◉</button><button class="icon-btn del" onclick="deleteApp('${a.id}')">⌫</button></div></td></tr>`}).join('')}
function filterApps(){const q=search.value.toLowerCase().trim(),c=course.value;renderApps(apps.filter(a=>{const s=[a.id,a.full_name,a.phone,a.course,a.email].join(' ').toLowerCase();return(!q||s.includes(q))&&(c==='ALL'||(a.course||'').includes(c))}))}
async function setStatus(id,status){try{await api('applications?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({status})});const a=apps.find(x=>x.id===id);if(a)a.status=status;filterApps()}catch(e){alert('স্ট্যাটাস আপডেট করা যায়নি।');loadApps()}}
async function deleteApp(id){if(!confirm('আপনি কি নিশ্চিতভাবে এই আবেদনটি মুছে ফেলতে চান?'))return;try{await api('applications?id=eq.'+encodeURIComponent(id),{method:'DELETE'});await loadApps()}catch(e){alert('ডিলিট করা যায়নি।')}}
function viewDetail(id){const a=apps.find(x=>x.id===id);if(!a)return;detail.innerHTML=`<div><span>Application ID</span><strong>${esc(a.id)}</strong></div><div><span>নাম</span><strong>${esc(a.full_name)}</strong></div><div><span>মোবাইল</span><strong>${esc(a.phone)}</strong></div><div><span>ই-মেইল</span><strong>${esc(a.email||'নাই')}</strong></div><div><span>কোর্স</span><strong>${esc(a.course)}</strong></div><div><span>অবস্থা</span><strong>${esc(a.status||'new')}</strong></div><div><span>তারিখ ও সময়</span><strong>${a.created_at?esc(new Date(a.created_at).toLocaleString('bn-BD')):'---'}</strong></div><div class="message"><span>ঠিকানা ও অতিরিক্ত তথ্য</span><div>${esc(a.message||'কোনো বার্তা নেই').replace(/\n/g,'<br>')}</div></div>`;detailModal.classList.add('open')}
function closeDetail(){detailModal.classList.remove('open')}
function openAdd(){addModal.classList.add('open')}
function closeAdd(){addModal.classList.remove('open')}
async function addApp(e){e.preventDefault();const body={full_name:mName.value.trim(),phone:mPhone.value.trim(),email:mEmail.value.trim()||null,course:mCourse.value,message:mMessage.value.trim()||null};try{await api('applications',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});closeAdd();e.target.reset();await loadApps();alert('✓ নতুন শিক্ষার্থী Supabase-এ যুক্ত হয়েছে!')}catch(err){alert('আবেদন সংরক্ষণ করা যায়নি।');console.error(err)}}
function exportCSV(){if(!apps.length)return alert('এক্সপোর্ট করার জন্য কোনো ডাটা নেই।');let csv='\uFEFFSL,Application ID,Full Name,Phone,Email,Course,Status,Created At,Message\n';apps.forEach((a,i)=>{const q=x=>'"'+String(x??'').replace(/"/g,'""').replace(/\n/g,' ')+'"';csv+=`${i+1},${q(a.id)},${q(a.full_name)},${q(a.phone)},${q(a.email)},${q(a.course)},${q(a.status||'new')},${q(a.created_at)},${q(a.message)}\n`});const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='Farabi_Applications_'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(u)}
function newMemoNo(){const n=1001+(memos.length||0);memoNo.value='MEMO-'+n;memoDate.value=new Date().toISOString().slice(0,10)}
async function loadMemos(){try{memos=await api('cash_memos?select=*&order=created_at.desc');renderMemos();newMemoNo()}catch(e){memoList.innerHTML='<div class="empty">মেমো লোড করা যায়নি।</div>';console.error(e)}}
function renderMemos(){if(!memos.length){memoList.innerHTML='<div class="empty">এখনও কোনো মেমো সেভ করা হয়নি।</div>';return}memoList.innerHTML=memos.slice(0,20).map(m=>`<div class="mini-row"><span><strong>${esc(m.memo_no)}</strong><br>${esc(m.customer_name)} • ${esc(m.service_type)}</span><span style="text-align:right"><strong>৳${Number(m.amount).toFixed(2)}</strong><br><button class="btn danger" onclick="deleteMemo('${m.id}')">মুছুন</button></span></div>`).join('')}
async function saveMemo(){const body={memo_no:memoNo.value.trim(),memo_date:memoDate.value,customer_name:memoName.value.trim(),customer_phone:memoPhone.value.trim()||null,service_type:memoService.value,amount:Number(memoAmount.value)||0,paid:Number(memoPaid.value)||0};if(!body.customer_name||!body.service_type)return alert('নাম ও সেবার বিবরণ দিন।');try{await api('cash_memos',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});await loadMemos();previewMemo();window.print()}catch(e){alert('মেমো Supabase-এ সেভ করা যায়নি।');console.error(e)}}
async function deleteMemo(id){if(!confirm('এই মেমো মুছে ফেলবেন?'))return;try{await api('cash_memos?id=eq.'+encodeURIComponent(id),{method:'DELETE'});await loadMemos()}catch(e){alert('মেমো ডিলিট করা যায়নি।')}}
function previewMemo(){pvNo.textContent=memoNo.value;pvDate.textContent=memoDate.value||'---';pvName.textContent=memoName.value||'---';pvPhone.textContent=memoPhone.value||'---';pvService.textContent=memoService.value;const a=Number(memoAmount.value)||0,p=Number(memoPaid.value)||0,d=Math.max(a-p,0);pvAmount.textContent=a+'/-';pvTotal.textContent=a+'/-';pvPaid.textContent=p+'/-';pvDue.textContent=d+'/-'}
window.addEventListener('DOMContentLoaded',()=>{loginForm.addEventListener('submit',login);logoutBtn.addEventListener('click',logout);document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab,b)));search.addEventListener('input',filterApps);course.addEventListener('change',filterApps);addBtn.addEventListener('click',openAdd);closeAdd.addEventListener('click',closeAdd);refreshBtn.addEventListener('click',loadApps);exportBtn.addEventListener('click',exportCSV);addForm.addEventListener('submit',addApp);closeDetail.addEventListener('click',closeDetail);saveMemoBtn.addEventListener('click',saveMemo);[memoName,memoPhone,memoAmount,memoPaid,memoDate].forEach(x=>x.addEventListener('input',previewMemo));memoService.addEventListener('change',previewMemo);if(sessionStorage.getItem('farabi_demo_admin')==='1')show();else{memoDate.value=new Date().toISOString().slice(0,10);previewMemo()}if(window.lucide)lucide.createIcons()});